### ISSUE TITLE
Question about resnet implementation

### ISSUE THREAD

**Issue by harshita1804** [suvoooo/Learn-TensorFlow#1]
from 2nd-5th stage why do we use the res_identity more than once? 
`#2nd stage 
  # frm here on only conv block and identity block, no pooling

  x = res_conv(x, s=1, filters=(64, 256))
  x = res_identity(x, filters=(64, 256))
  x = res_identity(x, filters=(64, 256))

  # 3rd stage

  x = res_conv(x, s=2, filters=(128, 512))
  x = res_identity(x, filters=(128, 512))
  x = res_identity(x, filters=(128, 512))
  x = res_identity(x, filters=(128, 512))

  # 4th stage

  x = res_conv(x, s=2, filters=(256, 1024))
  x = res_identity(x, filters=(256, 1024))
  x = res_identity(x, filters=(256, 1024))
  x = res_identity(x, filters=(256, 1024))
  x = res_identity(x, filters=(256, 1024))
  x = res_identity(x, filters=(256, 1024))

  # 5th stage

  x = res_conv(x, s=2, filters=(512, 2048))
  x = res_identity(x, filters=(512, 2048))
  x = res_identity(x, filters=(512, 2048))
`

**Comment by suvoooo** [comment]
I think if you read the [medium post](https://towardsdatascience.com/understand-and-implement-resnet-50-with-tensorflow-2-0-1190b9b52691) along with the paper, you will see that the convolution block is acting like pooling layer because of the stride=2. In the Resnet-34 architecture you will see layers like 3x3 conv 128/2 (this is conv block) and then many 3x3 conv 128 layers (these are identity blocks).  We calculate features via both identity and conv block but in conv block we reduce the input dimension. So we start a stage with convolution block and then stack the identity blocks.
