### ISSUE TITLE
`fit()` missing in your VGG-like model in Facial_Keypoint_Kaggle.ipynb script

### ISSUE THREAD

**Issue by Engeloid** [suvoooo/Learn-TensorFlow#3]
Hi, 
I am a Tensorflow noob and was wondering what is missing after the following compilation in the script:

```
# face_key_model.compile(loss='mse', 
#                        optimizer=sgd, 
#                        metrics=['acc'])
```

I was trying to fit with the following parameters:

```
face_key_model.fit(train_ims_clean, 
                    clean_keypoints_arr, 
                    validation_split= 0.05, 
                    batch_size=64, 
                    epochs=300, 
                    callbacks=[customCallbacks(), reduce_lr, lrdecay, earlystop],
                    verbose=0)
```
But I get an error message when I want to include earlystop:
```
  File "C:\Users\xxx\anaconda3\envs\Keras\lib\site-packages\keras\callbacks.py", line 285, in set_model
    callback.set_model(model)

AttributeError: 'function' object has no attribute 'set_model'
```

Once I omit `earlystop`, training does work, but the network fails miserably after a few epochs of training as presumably the weights shoot up to infinity (or minus infinity) and so does the loss..
Any help?

**Comment by suvoooo** [comment]
Hello, thanks for checking this out. 

First, regarding `earlystop`,  I defined it as a function so if you want to include earlystop in callbacks, you need to specify the 'mode' e.g `earlystop('acc')`. Below I shared a working version of the notebook that I just tried but I would still like to highlight some points regarding training. 

1. If we are using only the clean dataset, the sample size is too low for a reasonably deep network to capture features. That's why augmentation is so necessary for this project. 
2. You can reduce the number of layers (check the shared notebook) and increase the validation size a bit more so that the network can understand what to penalize. This is because without augmentation the sample size is....    
3. Not only mean squared error but you can also try MSE + Log MSE. 

```   from tensorflow.python.ops import math_ops
      def custom_loss(y_true, y_pred):
         msleObject = tf.keras.losses.MeanSquaredLogarithmicError()
         y_true = tf.cast(y_true, tf.float64)
         y_true = tf.add(y_true, 1e-9)
         y_pred = tf.add(y_pred, 1e-9)
         msleTensor = msleObject(y_true, y_pred)
         mseObject = tf.keras.losses.MeanSquaredError()
         mseTensor = mseObject(y_true, y_pred)
         mseTensor_m = tf.math.scalar_mul(5, mseTensor, name=None) #alpha is hyperparameter
         tot_loss = tf.add(msleTensor, mseTensor_m)
         return tot_loss 
   model.compile(..., loss=custom_loss)
```

[Here](https://colab.research.google.com/drive/1eEswuIu4SrfOr6mW87BEaaPCTngElLpZ?usp=sharing), I just went through the VGG16 part to check how bad it gets over epochs. 

happy learning and best!
